#!/bin/bash
current_user=$(whoami)
Linux_machine_o_s=$(uname -asnrvmpio)
free_and_used_space=$(free -lghtw)
CRP=$(ps -eh)
#ip_address= $(sudo ip addr show)
host_name=$(hostname -I)
ip_link=$(ip link show)
disk_usage=$(du -hc)
all_sockets=$(ss -arbipomsO --tos --tipcinfo)
long_host_name=$(hostname -A)
pid=$(pidof -cx -d "," bash)
user_activity_and_info=$(w)
default_eject_device=$( eject -d)
mounted_files=$(mount -l)
#monitor_dashboard_terminal=$(gtop) I think THE ISSUE Is I might have to redownlaod gtop
open_files_hard_limit=$(ulimit -Hn)
open_files_soft_limit=$(ulimit -Sn)
file_status_in_systems=$(stat * /)
system_uptime=$(uptime)
vmstat_info=$(vmstat)
iostat_info=$(iostat)

printf "Free and used space/memory in the system: %s\n" "$free_and_used_space"
echo "System info about Linux OS:" ${Linux_machine_o_s}
printf "The username of the current user in the Terminal: %s\n" "${current_user}"
printf "List current running processes:%s\n"  "${CRP}"
printf "Internal System IP address: %s\n" "${host_name}"
#printf "Another way to access IP: %s\n" "${ip_address}"
printf " link-layer information of all available devices (which have a driver loaded): %s\n" "${ip_link}"
printf "System Disk Usage/file size totals: %s\n" "${disk_usage}"
printf "Display all sockets: %s\n" "${all_sockets}"
printf "All long host names (FQDNs): %s\n" "${long_host_name}"
printf "Process IDs running in Bash System: %s\n:" "${pid}"
printf "User Details and Activity: %s\n" "${user_activity_and_info}"
printf "Default Eject Device: %s\n" "${default_eject_device}"
printf "Mounted files in my system: %s\n" "${mounted_files}"
printf "Execution Time:"
#printf "System_monitoring_dashboard_for_terminal:%s\n" "${system_monitoring_dashboard_for_terminal}"
printf "Open Files Hard Limit: %d\n" "${open_files_hard_limit}"
printf "Open Files Soft Limit: %d\n" "${open_files_soft_limit}"
printf "The maximum number of opened file descriptors on my Linux system:"
cat /proc/sys/fs/file-max
time -p
printf "display file system status:%s\n" "${file_status_in_systems}"
printf "The system running time, number of users & Load averages:%s\n" "${system_uptime}"
printf "Virtual Memory Static Tool:%s\n" "${vmstat_info}"
printf "Monitor CPU utilization, system input/output statistics for all the disks and partitions: %s\n" "${iostat_info}"
